apiVersion: v1
kind: Service
metadata:
  name: zomato-service
spec:
  type: LoadBalancer
  selector:
    app: zomato
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000

